{
  "text-color": "#d9d3dc",
  "background-color": "#17131a",
  "line-number-color": "#6f6878",
  "line-number-background-color": "#17131a",
  "text-styles": {
    "Normal": {
      "text-color": null,
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "Other": {
      "text-color": "#d9d3dc",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "Comment": {
      "text-color": "#6f6878",
      "background-color": null,
      "bold": false,
      "italic": true,
      "underline": false
    },
    "Documentation": {
      "text-color": "#6f6878",
      "background-color": null,
      "bold": false,
      "italic": true,
      "underline": false
    },
    "Annotation": {
      "text-color": "#6f6878",
      "background-color": null,
      "bold": false,
      "italic": true,
      "underline": false
    },
    "CommentVar": {
      "text-color": "#6f6878",
      "background-color": null,
      "bold": false,
      "italic": true,
      "underline": false
    },
    "Keyword": {
      "text-color": "#c58fa2",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "ControlFlow": {
      "text-color": "#c58fa2",
      "background-color": null,
      "bold": true,
      "italic": false,
      "underline": false
    },
    "Operator": {
      "text-color": "#a3999f",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "Function": {
      "text-color": "#8fa6c4",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "BuiltIn": {
      "text-color": "#8fa6c4",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "Import": {
      "text-color": "#c58fa2",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "Variable": {
      "text-color": "#d9d3dc",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "Attribute": {
      "text-color": "#a89bc4",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "String": {
      "text-color": "#9bb49e",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "VerbatimString": {
      "text-color": "#9bb49e",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "SpecialString": {
      "text-color": "#b0a97f",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "Char": {
      "text-color": "#9bb49e",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "Constant": {
      "text-color": "#c9a06d",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "SpecialChar": {
      "text-color": "#c9a06d",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "DecVal": {
      "text-color": "#c9a06d",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "BaseN": {
      "text-color": "#c9a06d",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "Float": {
      "text-color": "#c9a06d",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "DataType": {
      "text-color": "#a89bc4",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "Preprocessor": {
      "text-color": "#b58a63",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "Extension": {
      "text-color": "#a89bc4",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "Information": {
      "text-color": "#6f6878",
      "background-color": null,
      "bold": false,
      "italic": true,
      "underline": false
    },
    "Warning": {
      "text-color": "#c9a06d",
      "background-color": null,
      "bold": false,
      "italic": true,
      "underline": false
    },
    "Alert": {
      "text-color": "#cf6b81",
      "background-color": null,
      "bold": true,
      "italic": false,
      "underline": false
    },
    "Error": {
      "text-color": "#cf6b81",
      "background-color": null,
      "bold": true,
      "italic": false,
      "underline": false
    },
    "RegionMarker": {
      "text-color": "#6f6878",
      "background-color": null,
      "bold": false,
      "italic": true,
      "underline": false
    }
  }
}