{
  "text-color": "#e3dfff",
  "background-color": "#131327",
  "line-number-color": "#a599e9",
  "line-number-background-color": "#131327",
  "text-styles": {
    "Normal": {
      "text-color": null,
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "Other": {
      "text-color": "#a5ff90",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "Comment": {
      "text-color": "#b362ff",
      "background-color": null,
      "bold": false,
      "italic": true,
      "underline": false
    },
    "Documentation": {
      "text-color": "#b362ff",
      "background-color": null,
      "bold": false,
      "italic": true,
      "underline": false
    },
    "Annotation": {
      "text-color": "#b362ff",
      "background-color": null,
      "bold": false,
      "italic": true,
      "underline": false
    },
    "CommentVar": {
      "text-color": "#b362ff",
      "background-color": null,
      "bold": false,
      "italic": true,
      "underline": false
    },
    "Keyword": {
      "text-color": "#ff9d00",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "ControlFlow": {
      "text-color": "#ff9d00",
      "background-color": null,
      "bold": true,
      "italic": false,
      "underline": false
    },
    "Operator": {
      "text-color": "#ff9d00",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "Function": {
      "text-color": "#fad000",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "BuiltIn": {
      "text-color": "#fad000",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "Import": {
      "text-color": "#ff9d00",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "Variable": {
      "text-color": "#9effff",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "Attribute": {
      "text-color": "#9effff",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "String": {
      "text-color": "#a5ff90",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "VerbatimString": {
      "text-color": "#a5ff90",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "SpecialString": {
      "text-color": "#a5ff90",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "Char": {
      "text-color": "#a5ff90",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "Constant": {
      "text-color": "#ff628c",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "SpecialChar": {
      "text-color": "#ff628c",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "DecVal": {
      "text-color": "#ff628c",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "BaseN": {
      "text-color": "#ff628c",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "Float": {
      "text-color": "#ff628c",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "DataType": {
      "text-color": "#9effff",
      "background-color": null,
      "bold": true,
      "italic": false,
      "underline": false
    },
    "Preprocessor": {
      "text-color": "#ff9d00",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "Extension": {
      "text-color": "#e3dfff",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "Information": {
      "text-color": "#a599e9",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "Warning": {
      "text-color": "#fad000",
      "background-color": null,
      "bold": false,
      "italic": true,
      "underline": false
    },
    "Alert": {
      "text-color": "#ff628c",
      "background-color": null,
      "bold": true,
      "italic": false,
      "underline": false
    },
    "Error": {
      "text-color": "#ff628c",
      "background-color": null,
      "bold": true,
      "italic": false,
      "underline": false
    },
    "RegionMarker": {
      "text-color": "#a599e9",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    }
  }
}